### ISSUE TITLE
Showing error package "cohttp" doesn't exist in the current project  for ocaml-cohttp version 1.2.0

### ISSUE THREAD

**Issue by sajibtariq** [uccmisl/dashc#5]
Recently I have tried to install dashc but every time it showing error  "**Package "cohttp" doesn't exist in the current project** " while I run make command
I would be very grateful if kindly tell me the solution.
Thank you..

**Comment by jq5** [comment]
I have updated the configure file, so please do try and install again, if you are still interested.

The project has been tested in Ubuntu 18.04.03
